### ISSUE TITLE
Dark/night mode?

### ISSUE THREAD

**Issue by Silmathoron** [pietroalbini/sphinx-themes#1]
Hi there and thanks for the nice theme!
Your Readme mentions a dark/night mode, which caught my interest, (how) can this be used?

**Comment by emilyalbini** [comment]
[It was removed](https://github.com/pietroalbini/sphinx-themes/commit/55d30b94e67bc5970d8ed2e9dbefbc09e38876a7), but I don't remember *why* (it happened so long ago).

I'm not using the theme myself anymore, and I don't have the time to maintain it. If you want to add it back fork the theme :)
